[workspace]
members = [
    "ct",
    "rt",
]

[package]
name = "emit"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[dependencies.emit_rt]
path = "rt"

[dependencies.emit_ct]
path = "ct"

[dev-dependencies.serde]
version = "1"

[dev-dependencies.serde_derive]
version = "1"

[dev-dependencies.uuid]
version = "0.8"
features = ["v4", "serde"]

[dev-dependencies.emit_rt]
path = "rt"
features = ["std", "tracing", "serde"]

[dev-dependencies.trybuild]
version = "1"

[dev-dependencies.tracing]
version = "0.1"

[dev-dependencies.tracing-subscriber]
version = "0.2"
