[workspace]
members = [
    "rt"
]

[package]
name = "emit"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"
build = "build.rs"

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1"

[dependencies.quote]
version = "1"

[dependencies.syn]
version = "1"
features = ["full", "extra-traits", "visit-mut"]

[dependencies.thiserror]
version = "1"

[dependencies.fv-template]
git = "https://github.com/sval-rs/fv-template"

[dev-dependencies.serde]
version = "1"

[dev-dependencies.serde_derive]
version = "1"

[dev-dependencies.uuid]
version = "0.8"
features = ["v4", "serde"]

[dev-dependencies.emit_rt]
path = "rt"
features = ["std", "tracing", "serde"]

[dev-dependencies.trybuild]
version = "1"

[dev-dependencies.tracing]
version = "0.1"

[dev-dependencies.tracing-subscriber]
version = "0.2"
