[package]
name = "antlog_macros_rt"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[dependencies.log]
git = "https://github.com/KodrAus/log.git"
branch = "feat/antlog"
features = ["kv_unstable"]
