[package]
name = "emit_rt"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[features]
tracing = ["tracing-core"]
std = ["value-bag/std", "value-bag/error", "sval/std"]
serde = ["serde_lib", "value-bag/serde"]

[dependencies.value-bag]
version = "1.0.0-alpha.5"
features = ["sval"]

[dependencies.fv-template]
git = "https://github.com/sval-rs/fv-template"

[dependencies.sval]
version = "1.0.0-alpha.4"

[dependencies.sval_json]
version = "1.0.0-alpha.4"

[dependencies.serde_lib]
version = "1"
default-features = false
optional = true
package = "serde"

[dependencies.tracing-core]
version = "0.1"
default-features = false
optional = true
